version: "3"

services:
  ownfoil:
    container_name: ownfoil
    # image: a1ex4/ownfoil:develop
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # For write permission in /games directory
      - PUID=1000
      - PGID=1000
      # Uncomment to setup basic auth
      # - USERNAME=a1ex
      # - PASSWORD=
      # - ROOT_DIR=/games
      # - SAVE_ENABLED=true
    volumes:
      - '~/Downloads/ownfoil:/games'
    ports:
      - "8000:80"